### DISCUSSION TITLE
Environment specific paths

### DISCUSSION THREAD

**Discussion by m-kuhn** [opengisch/georama#103] [Ideas]
Sometimes it is interesting to have one project / set of layers that can be represented with data from different environments.
This can be different databases, urls or file paths. There are currently a few bandaids available to reroute this, depending on the environment (database: pg_service, urls: adding an http proxy or messing with hostnames/dns, paths: mounting different drives).

**It would be nice to be able to control the path in datasources based on environment variables**

The original .qgs project will currently always have literal paths stored in it, as QGIS doesn't have any functionality to make use of environment (or other) variables to construct paths. Ideally we'd change that but it's a non trivial task.

A much more feasible plan would be to be able to replace some paths into template placeholders which will then be replaced on Georama.

Let's assume that we have files stored on S3 with different prefixes for D: Development, I: Integration, P: Production. `https://something/\.amazonaws\.com/data/D/mydata.geoparquet`,  `https://something/\.amazonaws\.com/data/I/mydata.geoparquet`,  `https://something/\.amazonaws\.com/data/P/mydata.geoparquet`

We could have a regex-based pattern like the following that is used during the `.qgs` to `.json` conversion process (which is configured locally):

```yaml
replacement_rules:
  - pattern: r"https://something/\.amazonaws\.com/data/[A-Z]/(.*)",
    replacement: r"[https://something.amazonaws.com/data/{env.CURRENT_ENV}/\1](https://something.amazonaws.com/data/%7Benv.CURRENT_ENV%7D/%5C1)"
```

For ease of implementation, I'd just apply that on the complete `.json`. (sidenote: I guess could also add some jsonpath to specifiy more exactly where that should happen).

On Georama we would then resolve that when loading the layer and expor this environment variable, e.g. `CURRENT_ENV=P` for production.

The main challenge I see with that is that the converter which translates `.qgs` files to `.json` files needs configuration. If this is done in a CI/CD pipeline that's very well doable. If it's in a QGIS plugin that's run on multiple machines, it's harder to control that everyone has the configuration properly done.
